# ChatGPT helped me make these datasets
# ChatGPT taught me how to webscrape lololol
# All the Move Info is webscraped from https://pokemondb.net/move/all

import pickle

def main(): 
    pokemon = {'bulbasaur', 'ivysaur', 'venusaur', 'charmander', 'charmeleon', 'charizard', 'squirtle', 'wartortle', 'blastoise', 'caterpie', 'metapod', 'butterfree', 'weedle', 'kakuna', 'beedrill', 'pidgey', 'pidgeotto', 'pidgeot', 'rattata', 'raticate', 'spearow', 'fearow', 'ekans', 'arbok', 'pikachu', 'raichu', 'sandshrew', 'sandslash', 'nidoran', 'nidorina', 'nidoqueen', 'nidorino', 'nidoking', 'clefairy', 'clefable', 'vulpix', 'ninetales', 'jigglypuff', 'wigglytuff', 'zubat', 'golbat', 'oddish', 'gloom', 'vileplume', 'paras', 'parasect', 'venonat', 'venomoth', 'diglett', 'dugtrio', 'meowth', 'persian', 'psyduck', 'golduck', 'mankey', 'primeape', 'growlithe', 'arcanine', 'poliwag', 'poliwhirl', 'poliwrath', 'abra', 'kadabra', 'alakazam', 'machop', 'machoke', 'machamp', 'bellsprout', 'weepinbell', 'victreebel', 'tentacool', 'tentacruel', 'geodude', 'graveler', 'golem', 'ponyta', 'rapidash', 'slowpoke', 'slowbro', 'magnemite', 'magneton', 'farfetch’d', 'doduo', 'dodrio', 'seel', 'dewgong', 'grimer', 'muk', 'shellder', 'cloyster', 'gastly', 'haunter', 'gengar', 'onix', 'drowzee', 'hypno', 'krabby', 'kingler', 'voltorb', 'electrode', 'exeggcute', 'exeggutor', 'cubone', 'marowak', 'hitmonlee', 'hitmonchan', 'lickitung', 'koffing', 'weezing', 'rhyhorn', 'rhydon', 'chansey', 'tangela', 'kangaskhan', 'horsea', 'seadra', 'goldeen', 'seaking', 'staryu', 'starmie', 'mr. mime', 'scyther', 'jynx', 'electabuzz', 'magmar', 'pinsir', 'tauros', 'magikarp', 'gyarados', 'lapras', 'ditto', 'eevee', 'vaporeon', 'jolteon', 'flareon', 'porygon', 'omanyte', 'omastar', 'kabuto', 'kabutops', 'aerodactyl', 'snorlax', 'articuno', 'zapdos', 'moltres', 'dratini', 'dragonair', 'dragonite', 'mewtwo', 'mew'}

    with open('genOneNames', 'wb') as file:
        pickle.dump(pokemon, file)
    
    with open('genOneNames', 'rb') as file: 
        print(pickle.load(file))

    natureEffectDict = {
        'adamant': (1, 3),
        'bashful': (3, 3),
        'bold': (2, 1),
        'brave': (1, 5),
        'calm': (4, 1),
        'careful': (4, 3),
        'docile': (2, 2),
        'gentle': (4, 2),
        'hardy': (1, 1),
        'hasty': (5, 2),
        'impish': (2, 3),
        'jolly': (5, 3),
        'lax': (2, 4),
        'lonely': (1, 2),
        'mild': (3, 2),
        'modest': (3, 1),
        'naive': (5, 4),
        'naughty': (1, 4),
        'quiet': (3, 5),
        'quirky': (4, 4),
        'rash': (3, 4),
        'relaxed': (2, 5),
        'sassy': (4, 5),
        'serious': (5, 5),
        'timid': (5, 1)
    }

    with open('natureEffects', 'wb') as file:
        pickle.dump(natureEffectDict, file)

    with open('natureEffects', 'rb') as file: 
        print(pickle.load(file))

    movesMap = {
        "absorb": ['20', 'grass', 1], 
        "accelerock": ['40', 'rock', 0], 
        "acid": ['40', 'poison', 1], 
        "acid-armor": [0, 'poison', 2], 
        "acid-spray": ['40', 'poison', 1], 
        "acrobatics": ['55', 'flying', 0], 
        "acupressure": [0, 'normal', 2], 
        "aerial-ace": ['60', 'flying', 0], 
        "aeroblast": ['100', 'flying', 1], 
        "after-you": [0, 'normal', 2], 
        "agility": [0, 'psychic', 2], 
        "air-cutter": ['60', 'flying', 1], 
        "air-slash": ['75', 'flying', 1], 
        "alluring-voice": ['80', 'fairy', 1], 
        "ally-switch": [0, 'psychic', 2], 
        "amnesia": [0, 'psychic', 2], 
        "anchor-shot": ['80', 'steel', 0], 
        "ancient-power": ['60', 'rock', 1], 
        "apple-acid": ['80', 'grass', 1], 
        "aqua-cutter": ['70', 'water', 0], 
        "aqua-jet": ['40', 'water', 0], 
        "aqua-ring": [0, 'water', 2], 
        "aqua-step": ['80', 'water', 0], 
        "aqua-tail": ['90', 'water', 0], 
        "arm-thrust": ['15', 'fighting', 0], 
        "armor-cannon": ['120', 'fire', 1], 
        "aromatherapy": [0, 'grass', 2], 
        "aromatic-mist": [0, 'fairy', 2], 
        "assist": [0, 'normal', 2], 
        "assurance": ['60', 'dark', 0], 
        "astonish": ['30', 'ghost', 0], 
        "astral-barrage": ['120', 'ghost', 1], 
        "attack-order": ['90', 'bug', 0], 
        "attract": [0, 'normal', 2], 
        "aura-sphere": ['80', 'fighting', 1], 
        "aura-wheel": ['110', 'electric', 0], 
        "aurora-beam": ['65', 'ice', 1], 
        "aurora-veil": [0, 'ice', 2], 
        "autotomize": [0, 'steel', 2], 
        "avalanche": ['60', 'ice', 0], 
        "axe-kick": ['120', 'fighting', 0], 
        "baby-doll-eyes": [0, 'fairy', 2], 
        "baddy-bad": ['90', 'dark', 1], 
        "baneful-bunker": [0, 'poison', 2], 
        "barb-barrage": ['60', 'poison', 0], 
        "barrage": ['15', 'normal', 0], 
        "barrier": [0, 'psychic', 2], 
        "baton-pass": [0, 'normal', 2], 
        "beak-blast": ['100', 'flying', 0], 
        "beat-up": [0, 'dark', 0], 
        "belch": ['120', 'poison', 1], 
        "belly-drum": [0, 'normal', 2], 
        "bestow": [0, 'normal', 2], 
        "bide": [0, 'normal', 0], 
        "bind": ['15', 'normal', 0], 
        "bite": ['60', 'dark', 0], 
        "bitter-blade": ['90', 'fire', 0], 
        "bitter-malice": ['75', 'ghost', 1], 
        "blast-burn": ['150', 'fire', 1], 
        "blaze-kick": ['85', 'fire', 0], 
        "blazing-torque": ['80', 'fire', 0], 
        "bleakwind-storm": ['100', 'flying', 1], 
        "blizzard": ['110', 'ice', 1], 
        "block": [0, 'normal', 2], 
        "blood-moon": ['140', 'normal', 1], 
        "blue-flare": ['130', 'fire', 1], 
        "body-press": ['80', 'fighting', 0], 
        "body-slam": ['85', 'normal', 0], 
        "bolt-beak": ['85', 'electric', 0], 
        "bolt-strike": ['130', 'electric', 0], 
        "bone-club": ['65', 'ground', 0], 
        "bone-rush": ['25', 'ground', 0], 
        "bonemerang": ['50', 'ground', 0], 
        "boomburst": ['140', 'normal', 1], 
        "bounce": ['85', 'flying', 0], 
        "bouncy-bubble": ['90', 'water', 1], 
        "branch-poke": ['40', 'grass', 0], 
        "brave-bird": ['120', 'flying', 0], 
        "breaking-swipe": ['60', 'dragon', 0], 
        "brick-break": ['75', 'fighting', 0], 
        "brine": ['65', 'water', 1], 
        "brutal-swing": ['60', 'dark', 0], 
        "bubble": ['40', 'water', 1], 
        "bubble-beam": ['65', 'water', 1], 
        "bug-bite": ['60', 'bug', 0], 
        "bug-buzz": ['90', 'bug', 1], 
        "bulk-up": [0, 'fighting', 2], 
        "bulldoze": ['60', 'ground', 0], 
        "bullet-punch": ['40', 'steel', 0], 
        "bullet-seed": ['25', 'grass', 0], 
        "burn-up": ['130', 'fire', 1], 
        "burning-bulwark": [0, 'fire', 2], 
        "burning-jealousy": ['70', 'fire', 1], 
        "buzzy-buzz": ['90', 'electric', 1], 
        "calm-mind": [0, 'psychic', 2], 
        "camouflage": [0, 'normal', 2], 
        "captivate": [0, 'normal', 2], 
        "ceaseless-edge": ['65', 'dark', 0], 
        "celebrate": [0, 'normal', 2], 
        "charge": [0, 'electric', 2], 
        "charge-beam": ['50', 'electric', 1], 
        "charm": [0, 'fairy', 2], 
        "chatter": ['65', 'flying', 1], 
        "chilling-water": ['50', 'water', 1], 
        "chilly-reception": [0, 'ice', 2], 
        "chip-away": ['70', 'normal', 0], 
        "chloroblast": ['150', 'grass', 1], 
        "circle-throw": ['60', 'fighting', 0], 
        "clamp": ['35', 'water', 0], 
        "clanging-scales": ['110', 'dragon', 1], 
        "clangorous-soul": [0, 'dragon', 2], 
        "clear-smog": ['50', 'poison', 1], 
        "close-combat": ['120', 'fighting', 0], 
        "coaching": [0, 'fighting', 2], 
        "coil": [0, 'poison', 2], 
        "collision-course": ['100', 'fighting', 0], 
        "combat-torque": ['100', 'fighting', 0], 
        "comet-punch": ['18', 'normal', 0], 
        "comeuppance": [0, 'dark', 0], 
        "confide": [0, 'normal', 2], 
        "confuse-ray": [0, 'ghost', 2], 
        "confusion": ['50', 'psychic', 1], 
        "constrict": ['10', 'normal', 0], 
        "conversion": [0, 'normal', 2], 
        "conversion-2": [0, 'normal', 2], 
        "copycat": [0, 'normal', 2], 
        "core-enforcer": ['100', 'dragon', 1], 
        "corrosive-gas": [0, 'poison', 2], 
        "cosmic-power": [0, 'psychic', 2], 
        "cotton-guard": [0, 'grass', 2], 
        "cotton-spore": [0, 'grass', 2], 
        "counter": [0, 'fighting', 0], 
        "court-change": [0, 'normal', 2], 
        "covet": ['60', 'normal', 0], 
        "crabhammer": ['100', 'water', 0], 
        "crafty-shield": [0, 'fairy', 2], 
        "cross-chop": ['100', 'fighting', 0], 
        "cross-poison": ['70', 'poison', 0], 
        "crunch": ['80', 'dark', 0], 
        "crush-claw": ['75', 'normal', 0], 
        "crush-grip": [0, 'normal', 0], 
        "curse": [0, 'ghost', 2], 
        "cut": ['50', 'normal', 0], 
        "dark-pulse": ['80', 'dark', 1], 
        "dark-void": [0, 'dark', 2], 
        "darkest-lariat": ['85', 'dark', 0], 
        "dazzling-gleam": ['80', 'fairy', 1], 
        "decorate": [0, 'fairy', 2], 
        "defend-order": [0, 'bug', 2], 
        "defense-curl": [0, 'normal', 2], 
        "defog": [0, 'flying', 2], 
        "destiny-bond": [0, 'ghost', 2], 
        "detect": [0, 'fighting', 2], 
        "diamond-storm": ['100', 'rock', 0], 
        "dig": ['80', 'ground', 0], 
        "dire-claw": ['80', 'poison', 0], 
        "disable": [0, 'normal', 2], 
        "disarming-voice": ['40', 'fairy', 1], 
        "discharge": ['80', 'electric', 1], 
        "dive": ['80', 'water', 0], 
        "dizzy-punch": ['70', 'normal', 0], 
        "doodle": [0, 'normal', 2], 
        "doom-desire": ['140', 'steel', 1], 
        "double-hit": ['35', 'normal', 0], 
        "double-iron-bash": ['60', 'steel', 0], 
        "double-kick": ['30', 'fighting', 0], 
        "double-shock": ['120', 'electric', 0], 
        "double-slap": ['15', 'normal', 0], 
        "double-team": [0, 'normal', 2], 
        "double-edge": ['120', 'normal', 0], 
        "draco-meteor": ['130', 'dragon', 1], 
        "dragon-ascent": ['120', 'flying', 0], 
        "dragon-breath": ['60', 'dragon', 1], 
        "dragon-cheer": [0, 'dragon', 2], 
        "dragon-claw": ['80', 'dragon', 0], 
        "dragon-dance": [0, 'dragon', 2], 
        "dragon-darts": ['50', 'dragon', 0], 
        "dragon-energy": ['150', 'dragon', 1], 
        "dragon-hammer": ['90', 'dragon', 0], 
        "dragon-pulse": ['85', 'dragon', 1], 
        "dragon-rage": [0, 'dragon', 1], 
        "dragon-rush": ['100', 'dragon', 0], 
        "dragon-tail": ['60', 'dragon', 0], 
        "drain-punch": ['75', 'fighting', 0], 
        "draining-kiss": ['50', 'fairy', 1], 
        "dream-eater": ['100', 'psychic', 1], 
        "drill-peck": ['80', 'flying', 0], 
        "drill-run": ['80', 'ground', 0], 
        "drum-beating": ['80', 'grass', 0], 
        "dual-chop": ['40', 'dragon', 0], 
        "dual-wingbeat": ['40', 'flying', 0], 
        "dynamic-punch": ['100', 'fighting', 0], 
        "earth-power": ['90', 'ground', 1], 
        "earthquake": ['100', 'ground', 0], 
        "echoed-voice": ['40', 'normal', 1], 
        "eerie-impulse": [0, 'electric', 2], 
        "eerie-spell": ['80', 'psychic', 1], 
        "egg-bomb": ['100', 'normal', 0], 
        "electric-terrain": [0, 'electric', 2], 
        "electrify": [0, 'electric', 2], 
        "electro-ball": [0, 'electric', 1], 
        "electro-drift": ['100', 'electric', 1], 
        "electro-shot": ['130', 'electric', 1], 
        "electroweb": ['55', 'electric', 1], 
        "embargo": [0, 'dark', 2], 
        "ember": ['40', 'fire', 1], 
        "encore": [0, 'normal', 2], 
        "endeavor": [0, 'normal', 0], 
        "endure": [0, 'normal', 2], 
        "energy-ball": ['90', 'grass', 1], 
        "entrainment": [0, 'normal', 2], 
        "eruption": ['150', 'fire', 1], 
        "esper-wing": ['80', 'psychic', 1], 
        "eternabeam": ['160', 'dragon', 1], 
        "expanding-force": ['80', 'psychic', 1], 
        "explosion": ['250', 'normal', 0], 
        "extrasensory": ['80', 'psychic', 1], 
        "extreme-speed": ['80', 'normal', 0], 
        "facade": ['70', 'normal', 0], 
        "fairy-lock": [0, 'fairy', 2], 
        "fairy-wind": ['40', 'fairy', 1], 
        "fake-out": ['40', 'normal', 0], 
        "fake-tears": [0, 'dark', 2], 
        "false-surrender": ['80', 'dark', 0], 
        "false-swipe": ['40', 'normal', 0], 
        "feather-dance": [0, 'flying', 2], 
        "feint": ['30', 'normal', 0], 
        "feint-attack": ['60', 'dark', 0], 
        "fell-stinger": ['50', 'bug', 0], 
        "fickle-beam": ['80', 'dragon', 1], 
        "fiery-dance": ['80', 'fire', 1], 
        "fiery-wrath": ['90', 'dark', 1], 
        "fillet-away": [0, 'normal', 2], 
        "final-gambit": [0, 'fighting', 1], 
        "fire-blast": ['110', 'fire', 1], 
        "fire-fang": ['65', 'fire', 0], 
        "fire-lash": ['80', 'fire', 0], 
        "fire-pledge": ['80', 'fire', 1], 
        "fire-punch": ['75', 'fire', 0], 
        "fire-spin": ['35', 'fire', 1], 
        "first-impression": ['90', 'bug', 0], 
        "fishious-rend": ['85', 'water', 0], 
        "fissure": [0, 'ground', 0], 
        "flail": [0, 'normal', 0], 
        "flame-burst": ['70', 'fire', 1], 
        "flame-charge": ['50', 'fire', 0], 
        "flame-wheel": ['60', 'fire', 0], 
        "flamethrower": ['90', 'fire', 1], 
        "flare-blitz": ['120', 'fire', 0], 
        "flash": [0, 'normal', 2], 
        "flash-cannon": ['80', 'steel', 1], 
        "flatter": [0, 'dark', 2], 
        "fleur-cannon": ['130', 'fairy', 1], 
        "fling": [0, 'dark', 0], 
        "flip-turn": ['60', 'water', 0], 
        "floaty-fall": ['90', 'flying', 0], 
        "floral-healing": [0, 'fairy', 2], 
        "flower-shield": [0, 'fairy', 2], 
        "flower-trick": ['70', 'grass', 0], 
        "fly": ['90', 'flying', 0], 
        "flying-press": ['100', 'fighting', 0], 
        "focus-blast": ['120', 'fighting', 1], 
        "focus-energy": [0, 'normal', 2], 
        "focus-punch": ['150', 'fighting', 0], 
        "follow-me": [0, 'normal', 2], 
        "force-palm": ['60', 'fighting', 0], 
        "foresight": [0, 'normal', 2], 
        "forest's-curse": [0, 'grass', 2], 
        "foul-play": ['95', 'dark', 0], 
        "freeze-shock": ['140', 'ice', 0], 
        "freeze-dry": ['70', 'ice', 1], 
        "freezing-glare": ['90', 'psychic', 1], 
        "freezy-frost": ['90', 'ice', 1], 
        "frenzy-plant": ['150', 'grass', 1], 
        "frost-breath": ['60', 'ice', 1], 
        "frustration": [0, 'normal', 0], 
        "fury-attack": ['15', 'normal', 0], 
        "fury-cutter": ['40', 'bug', 0], 
        "fury-swipes": ['18', 'normal', 0], 
        "fusion-bolt": ['100', 'electric', 0], 
        "fusion-flare": ['100', 'fire', 1], 
        "future-sight": ['120', 'psychic', 1], 
        "gastro-acid": [0, 'poison', 2], 
        "gear-grind": ['50', 'steel', 0], 
        "gear-up": [0, 'steel', 2], 
        "geomancy": [0, 'fairy', 2], 
        "giga-drain": ['75', 'grass', 1], 
        "giga-impact": ['150', 'normal', 0], 
        "gigaton-hammer": ['160', 'steel', 0], 
        "glacial-lance": ['120', 'ice', 0], 
        "glaciate": ['65', 'ice', 1], 
        "glaive-rush": ['120', 'dragon', 0], 
        "glare": [0, 'normal', 2], 
        "glitzy-glow": ['90', 'psychic', 1], 
        "grass-knot": [0, 'grass', 1], 
        "grass-pledge": ['80', 'grass', 1], 
        "grass-whistle": [0, 'grass', 2], 
        "grassy-glide": ['55', 'grass', 0], 
        "grassy-terrain": [0, 'grass', 2], 
        "grav-apple": ['80', 'grass', 0], 
        "gravity": [0, 'psychic', 2], 
        "growl": [0, 'normal', 2], 
        "growth": [0, 'normal', 2], 
        "grudge": [0, 'ghost', 2], 
        "guard-split": [0, 'psychic', 2], 
        "guard-swap": [0, 'psychic', 2], 
        "guardian-of-alola": [0, 'fairy', 1], 
        "guillotine": [0, 'normal', 0], 
        "gunk-shot": ['120', 'poison', 0], 
        "gust": ['40', 'flying', 1], 
        "gyro-ball": [0, 'steel', 0], 
        "hail": [0, 'ice', 2], 
        "hammer-arm": ['100', 'fighting', 0], 
        "happy-hour": [0, 'normal', 2], 
        "hard-press": [0, 'steel', 0], 
        "harden": [0, 'normal', 2], 
        "haze": [0, 'ice', 2], 
        "head-charge": ['120', 'normal', 0], 
        "head-smash": ['150', 'rock', 0], 
        "headbutt": ['70', 'normal', 0], 
        "headlong-rush": ['120', 'ground', 0], 
        "heal-bell": [0, 'normal', 2], 
        "heal-block": [0, 'psychic', 2], 
        "heal-order": [0, 'bug', 2], 
        "heal-pulse": [0, 'psychic', 2], 
        "healing-wish": [0, 'psychic', 2], 
        "heart-stamp": ['60', 'psychic', 0], 
        "heart-swap": [0, 'psychic', 2], 
        "heat-crash": [0, 'fire', 0], 
        "heat-wave": ['95', 'fire', 1], 
        "heavy-slam": [0, 'steel', 0], 
        "helping-hand": [0, 'normal', 2], 
        "hex": ['65', 'ghost', 1], 
        "hidden-power": ['60', 'normal', 1], 
        "high-horsepower": ['95', 'ground', 0], 
        "high-jump-kick": ['130', 'fighting', 0], 
        "hold-back": ['40', 'normal', 0], 
        "hold-hands": [0, 'normal', 2], 
        "hone-claws": [0, 'dark', 2], 
        "horn-attack": ['65', 'normal', 0], 
        "horn-drill": [0, 'normal', 0], 
        "horn-leech": ['75', 'grass', 0], 
        "howl": [0, 'normal', 2], 
        "hurricane": ['110', 'flying', 1], 
        "hydro-cannon": ['150', 'water', 1], 
        "hydro-pump": ['110', 'water', 1], 
        "hydro-steam": ['80', 'water', 1], 
        "hyper-beam": ['150', 'normal', 1], 
        "hyper-drill": ['100', 'normal', 0], 
        "hyper-fang": ['80', 'normal', 0], 
        "hyper-voice": ['90', 'normal', 1], 
        "hyperspace-fury": ['100', 'dark', 0], 
        "hyperspace-hole": ['80', 'psychic', 1], 
        "hypnosis": [0, 'psychic', 2], 
        "ice-ball": ['30', 'ice', 0], 
        "ice-beam": ['90', 'ice', 1], 
        "ice-burn": ['140', 'ice', 1], 
        "ice-fang": ['65', 'ice', 0], 
        "ice-hammer": ['100', 'ice', 0], 
        "ice-punch": ['75', 'ice', 0], 
        "ice-shard": ['40', 'ice', 0], 
        "ice-spinner": ['80', 'ice', 0], 
        "icicle-crash": ['85', 'ice', 0], 
        "icicle-spear": ['25', 'ice', 0], 
        "icy-wind": ['55', 'ice', 1], 
        "imprison": [0, 'psychic', 2], 
        "incinerate": ['60', 'fire', 1], 
        "infernal-parade": ['60', 'ghost', 1], 
        "inferno": ['100', 'fire', 1], 
        "infestation": ['20', 'bug', 1], 
        "ingrain": [0, 'grass', 2], 
        "instruct": [0, 'psychic', 2], 
        "ion-deluge": [0, 'electric', 2], 
        "iron-defense": [0, 'steel', 2], 
        "iron-head": ['80', 'steel', 0], 
        "iron-tail": ['100', 'steel', 0], 
        "ivy-cudgel": ['100', 'grass', 0], 
        "jaw-lock": ['80', 'dark', 0], 
        "jet-punch": ['60', 'water', 0], 
        "judgment": ['100', 'normal', 1], 
        "jump-kick": ['100', 'fighting', 0], 
        "jungle-healing": [0, 'grass', 2], 
        "karate-chop": ['50', 'fighting', 0], 
        "kinesis": [0, 'psychic', 2], 
        "king's-shield": [0, 'steel', 2], 
        "knock-off": ['65', 'dark', 0], 
        "kowtow-cleave": ['85', 'dark', 0], 
        "land's-wrath": ['90', 'ground', 0], 
        "laser-focus": [0, 'normal', 2], 
        "lash-out": ['75', 'dark', 0], 
        "last-resort": ['140', 'normal', 0], 
        "last-respects": ['50', 'ghost', 0], 
        "lava-plume": ['80', 'fire', 1], 
        "leaf-blade": ['90', 'grass', 0], 
        "leaf-storm": ['130', 'grass', 1], 
        "leaf-tornado": ['65', 'grass', 1], 
        "leafage": ['40', 'grass', 0], 
        "leech-life": ['80', 'bug', 0], 
        "leech-seed": [0, 'grass', 2], 
        "leer": [0, 'normal', 2], 
        "lick": ['30', 'ghost', 0], 
        "life-dew": [0, 'water', 2], 
        "light-of-ruin": ['140', 'fairy', 1], 
        "light-screen": [0, 'psychic', 2], 
        "liquidation": ['85', 'water', 0], 
        "lock-on": [0, 'normal', 2], 
        "lovely-kiss": [0, 'normal', 2], 
        "low-kick": [0, 'fighting', 0], 
        "low-sweep": ['65', 'fighting', 0], 
        "lucky-chant": [0, 'normal', 2], 
        "lumina-crash": ['80', 'psychic', 1], 
        "lunar-blessing": [0, 'psychic', 2], 
        "lunar-dance": [0, 'psychic', 2], 
        "lunge": ['80', 'bug', 0], 
        "luster-purge": ['95', 'psychic', 1], 
        "mach-punch": ['40', 'fighting', 0], 
        "magic-coat": [0, 'psychic', 2], 
        "magic-powder": [0, 'psychic', 2], 
        "magic-room": [0, 'psychic', 2], 
        "magical-leaf": ['60', 'grass', 1], 
        "magical-torque": ['100', 'fairy', 0], 
        "magma-storm": ['100', 'fire', 1], 
        "magnet-bomb": ['60', 'steel', 0], 
        "magnet-rise": [0, 'electric', 2], 
        "magnetic-flux": [0, 'electric', 2], 
        "magnitude": [0, 'ground', 0], 
        "make-it-rain": ['120', 'steel', 1], 
        "malignant-chain": ['100', 'poison', 1], 
        "mat-block": [0, 'fighting', 2], 
        "matcha-gotcha": ['80', 'grass', 1], 
        "me-first": [0, 'normal', 2], 
        "mean-look": [0, 'normal', 2], 
        "meditate": [0, 'psychic', 2], 
        "mega-drain": ['40', 'grass', 1], 
        "mega-kick": ['120', 'normal', 0], 
        "mega-punch": ['80', 'normal', 0], 
        "megahorn": ['120', 'bug', 0], 
        "memento": [0, 'dark', 2], 
        "metal-burst": [0, 'steel', 0], 
        "metal-claw": ['50', 'steel', 0], 
        "metal-sound": [0, 'steel', 2], 
        "meteor-assault": ['150', 'fighting', 0], 
        "meteor-beam": ['120', 'rock', 1], 
        "meteor-mash": ['90', 'steel', 0], 
        "metronome": [0, 'normal', 2], 
        "mighty-cleave": ['95', 'rock', 0], 
        "milk-drink": [0, 'normal', 2], 
        "mimic": [0, 'normal', 2], 
        "mind-blown": ['150', 'fire', 1], 
        "mind-reader": [0, 'normal', 2], 
        "minimize": [0, 'normal', 2], 
        "miracle-eye": [0, 'psychic', 2], 
        "mirror-coat": [0, 'psychic', 1], 
        "mirror-move": [0, 'flying', 2], 
        "mirror-shot": ['65', 'steel', 1], 
        "mist": [0, 'ice', 2], 
        "mist-ball": ['95', 'psychic', 1], 
        "misty-explosion": ['100', 'fairy', 1], 
        "misty-terrain": [0, 'fairy', 2], 
        "moonblast": ['95', 'fairy', 1], 
        "moongeist-beam": ['100', 'ghost', 1], 
        "moonlight": [0, 'fairy', 2], 
        "morning-sun": [0, 'normal', 2], 
        "mortal-spin": ['30', 'poison', 0], 
        "mountain-gale": ['100', 'ice', 0], 
        "mud-bomb": ['65', 'ground', 1], 
        "mud-shot": ['55', 'ground', 1], 
        "mud-sport": [0, 'ground', 2], 
        "mud-slap": ['20', 'ground', 1], 
        "muddy-water": ['90', 'water', 1], 
        "multi-attack": ['120', 'normal', 0], 
        "mystical-fire": ['75', 'fire', 1], 
        "mystical-power": ['70', 'psychic', 1], 
        "nasty-plot": [0, 'dark', 2], 
        "natural-gift": [0, 'normal', 0], 
        "nature-power": [0, 'normal', 2], 
        "nature's-madness": [0, 'fairy', 1], 
        "needle-arm": ['60', 'grass', 0], 
        "night-daze": ['85', 'dark', 1], 
        "night-shade": [0, 'ghost', 1], 
        "night-slash": ['70', 'dark', 0], 
        "nightmare": [0, 'ghost', 2], 
        "no-retreat": [0, 'fighting', 2], 
        "noble-roar": [0, 'normal', 2], 
        "noxious-torque": ['100', 'poison', 0], 
        "nuzzle": ['20', 'electric', 0], 
        "oblivion-wing": ['80', 'flying', 1], 
        "obstruct": [0, 'dark', 2], 
        "octazooka": ['65', 'water', 1], 
        "octolock": [0, 'fighting', 2], 
        "odor-sleuth": [0, 'normal', 2], 
        "ominous-wind": ['60', 'ghost', 1], 
        "order-up": ['80', 'dragon', 0], 
        "origin-pulse": ['110', 'water', 1], 
        "outrage": ['120', 'dragon', 0], 
        "overdrive": ['80', 'electric', 1], 
        "overheat": ['130', 'fire', 1], 
        "pain-split": [0, 'normal', 2], 
        "parabolic-charge": ['65', 'electric', 1], 
        "parting-shot": [0, 'dark', 2], 
        "pay-day": ['40', 'normal', 0], 
        "payback": ['50', 'dark', 0], 
        "peck": ['35', 'flying', 0], 
        "perish-song": [0, 'normal', 2], 
        "petal-blizzard": ['90', 'grass', 0], 
        "petal-dance": ['120', 'grass', 1], 
        "phantom-force": ['90', 'ghost', 0], 
        "photon-geyser": ['100', 'psychic', 1], 
        "pika-papow": [0, 'electric', 1], 
        "pin-missile": ['25', 'bug', 0], 
        "plasma-fists": ['100', 'electric', 0], 
        "play-nice": [0, 'normal', 2], 
        "play-rough": ['90', 'fairy', 0], 
        "pluck": ['60', 'flying', 0], 
        "poison-fang": ['50', 'poison', 0], 
        "poison-gas": [0, 'poison', 2], 
        "poison-jab": ['80', 'poison', 0], 
        "poison-powder": [0, 'poison', 2], 
        "poison-sting": ['15', 'poison', 0], 
        "poison-tail": ['50', 'poison', 0], 
        "pollen-puff": ['90', 'bug', 1], 
        "poltergeist": ['110', 'ghost', 0], 
        "population-bomb": ['20', 'normal', 0], 
        "pounce": ['50', 'bug', 0], 
        "pound": ['40', 'normal', 0], 
        "powder": [0, 'bug', 2], 
        "powder-snow": ['40', 'ice', 1], 
        "power-gem": ['80', 'rock', 1], 
        "power-shift": [0, 'normal', 2], 
        "power-split": [0, 'psychic', 2], 
        "power-swap": [0, 'psychic', 2], 
        "power-trick": [0, 'psychic', 2], 
        "power-trip": ['20', 'dark', 0], 
        "power-whip": ['120', 'grass', 0], 
        "power-up-punch": ['40', 'fighting', 0], 
        "precipice-blades": ['120', 'ground', 0], 
        "present": [0, 'normal', 0], 
        "prismatic-laser": ['160', 'psychic', 1], 
        "protect": [0, 'normal', 2], 
        "psybeam": ['65', 'psychic', 1], 
        "psyblade": ['80', 'psychic', 0], 
        "psych-up": [0, 'normal', 2], 
        "psychic": ['90', 'psychic', 1], 
        "psychic-fangs": ['85', 'psychic', 0], 
        "psychic-noise": ['75', 'psychic', 1], 
        "psychic-terrain": [0, 'psychic', 2], 
        "psycho-boost": ['140', 'psychic', 1], 
        "psycho-cut": ['70', 'psychic', 0], 
        "psycho-shift": [0, 'psychic', 2], 
        "psyshield-bash": ['70', 'psychic', 0], 
        "psyshock": ['80', 'psychic', 1], 
        "psystrike": ['100', 'psychic', 1], 
        "psywave": [0, 'psychic', 1], 
        "punishment": [0, 'dark', 0], 
        "purify": [0, 'poison', 2], 
        "pursuit": ['40', 'dark', 0], 
        "pyro-ball": ['120', 'fire', 0], 
        "quash": [0, 'dark', 2], 
        "quick-attack": ['40', 'normal', 0], 
        "quick-guard": [0, 'fighting', 2], 
        "quiver-dance": [0, 'bug', 2], 
        "rage": ['20', 'normal', 0], 
        "rage-fist": ['50', 'ghost', 0], 
        "rage-powder": [0, 'bug', 2], 
        "raging-bull": ['90', 'normal', 0], 
        "raging-fury": ['120', 'fire', 0], 
        "rain-dance": [0, 'water', 2], 
        "rapid-spin": ['50', 'normal', 0], 
        "razor-leaf": ['55', 'grass', 0], 
        "razor-shell": ['75', 'water', 0], 
        "razor-wind": ['80', 'normal', 1], 
        "recover": [0, 'normal', 2], 
        "recycle": [0, 'normal', 2], 
        "reflect": [0, 'psychic', 2], 
        "reflect-type": [0, 'normal', 2], 
        "refresh": [0, 'normal', 2], 
        "relic-song": ['75', 'normal', 1], 
        "rest": [0, 'psychic', 2], 
        "retaliate": ['70', 'normal', 0], 
        "return": [0, 'normal', 0], 
        "revelation-dance": ['90', 'normal', 1], 
        "revenge": ['60', 'fighting', 0], 
        "reversal": [0, 'fighting', 0], 
        "revival-blessing": [0, 'normal', 2], 
        "rising-voltage": ['70', 'electric', 1], 
        "roar": [0, 'normal', 2], 
        "roar-of-time": ['150', 'dragon', 1], 
        "rock-blast": ['25', 'rock', 0], 
        "rock-climb": ['90', 'normal', 0], 
        "rock-polish": [0, 'rock', 2], 
        "rock-slide": ['75', 'rock', 0], 
        "rock-smash": ['40', 'fighting', 0], 
        "rock-throw": ['50', 'rock', 0], 
        "rock-tomb": ['60', 'rock', 0], 
        "rock-wrecker": ['150', 'rock', 0], 
        "role-play": [0, 'psychic', 2], 
        "rolling-kick": ['60', 'fighting', 0], 
        "rollout": ['30', 'rock', 0], 
        "roost": [0, 'flying', 2], 
        "rototiller": [0, 'ground', 2], 
        "round": ['60', 'normal', 1], 
        "ruination": [0, 'dark', 1], 
        "sacred-fire": ['100', 'fire', 0], 
        "sacred-sword": ['90', 'fighting', 0], 
        "safeguard": [0, 'normal', 2], 
        "salt-cure": ['40', 'rock', 0], 
        "sand-attack": [0, 'ground', 2], 
        "sand-tomb": ['35', 'ground', 0], 
        "sandsear-storm": ['100', 'ground', 1], 
        "sandstorm": [0, 'rock', 2], 
        "sappy-seed": ['90', 'grass', 0], 
        "scald": ['80', 'water', 1], 
        "scale-shot": ['25', 'dragon', 0], 
        "scary-face": [0, 'normal', 2], 
        "scorching-sands": ['70', 'ground', 1], 
        "scratch": ['40', 'normal', 0], 
        "screech": [0, 'normal', 2], 
        "searing-shot": ['100', 'fire', 1], 
        "secret-power": ['70', 'normal', 0], 
        "secret-sword": ['85', 'fighting', 1], 
        "seed-bomb": ['80', 'grass', 0], 
        "seed-flare": ['120', 'grass', 1], 
        "seismic-toss": [0, 'fighting', 0], 
        "self-destruct": ['200', 'normal', 0], 
        "shadow-ball": ['80', 'ghost', 1], 
        "shadow-bone": ['85', 'ghost', 0], 
        "shadow-claw": ['70', 'ghost', 0], 
        "shadow-force": ['120', 'ghost', 0], 
        "shadow-punch": ['60', 'ghost', 0], 
        "shadow-sneak": ['40', 'ghost', 0], 
        "sharpen": [0, 'normal', 2], 
        "shed-tail": [0, 'normal', 2], 
        "sheer-cold": [0, 'ice', 1], 
        "shell-side-arm": ['90', 'poison', 1], 
        "shell-smash": [0, 'normal', 2], 
        "shell-trap": ['150', 'fire', 1], 
        "shelter": [0, 'steel', 2], 
        "shift-gear": [0, 'steel', 2], 
        "shock-wave": ['60', 'electric', 1], 
        "shore-up": [0, 'ground', 2], 
        "signal-beam": ['75', 'bug', 1], 
        "silk-trap": [0, 'bug', 2], 
        "silver-wind": ['60', 'bug', 1], 
        "simple-beam": [0, 'normal', 2], 
        "sing": [0, 'normal', 2], 
        "sizzly-slide": ['90', 'fire', 0], 
        "sketch": [0, 'normal', 2], 
        "skill-swap": [0, 'psychic', 2], 
        "skitter-smack": ['70', 'bug', 0], 
        "skull-bash": ['130', 'normal', 0], 
        "sky-attack": ['140', 'flying', 0], 
        "sky-drop": ['60', 'flying', 0], 
        "sky-uppercut": ['85', 'fighting', 0], 
        "slack-off": [0, 'normal', 2], 
        "slam": ['80', 'normal', 0], 
        "slash": ['70', 'normal', 0], 
        "sleep-powder": [0, 'grass', 2], 
        "sleep-talk": [0, 'normal', 2], 
        "sludge": ['65', 'poison', 1], 
        "sludge-bomb": ['90', 'poison', 1], 
        "sludge-wave": ['95', 'poison', 1], 
        "smack-down": ['50', 'rock', 0], 
        "smart-strike": ['70', 'steel', 0], 
        "smelling-salts": ['70', 'normal', 0], 
        "smog": ['30', 'poison', 1], 
        "smokescreen": [0, 'normal', 2], 
        "snap-trap": ['35', 'grass', 0], 
        "snarl": ['55', 'dark', 1], 
        "snatch": [0, 'dark', 2], 
        "snipe-shot": ['80', 'water', 1], 
        "snore": ['50', 'normal', 1], 
        "snowscape": [0, 'ice', 2], 
        "soak": [0, 'water', 2], 
        "soft-boiled": [0, 'normal', 2], 
        "solar-beam": ['120', 'grass', 1], 
        "solar-blade": ['125', 'grass', 0], 
        "sonic-boom": [0, 'normal', 1], 
        "spacial-rend": ['100', 'dragon', 1], 
        "spark": ['65', 'electric', 0], 
        "sparkling-aria": ['90', 'water', 1], 
        "sparkly-swirl": ['90', 'fairy', 1], 
        "spectral-thief": ['90', 'ghost', 0], 
        "speed-swap": [0, 'psychic', 2], 
        "spicy-extract": [0, 'grass', 2], 
        "spider-web": [0, 'bug', 2], 
        "spike-cannon": ['20', 'normal', 0], 
        "spikes": [0, 'ground', 2], 
        "spiky-shield": [0, 'grass', 2], 
        "spin-out": ['100', 'steel', 0], 
        "spirit-break": ['75', 'fairy', 0], 
        "spirit-shackle": ['80', 'ghost', 0], 
        "spit-up": [0, 'normal', 1], 
        "spite": [0, 'ghost', 2], 
        "splash": [0, 'normal', 2], 
        "splishy-splash": ['90', 'water', 1], 
        "spore": [0, 'grass', 2], 
        "spotlight": [0, 'normal', 2], 
        "springtide-storm": ['100', 'fairy', 1], 
        "stealth-rock": [0, 'rock', 2], 
        "steam-eruption": ['110', 'water', 1], 
        "steamroller": ['65', 'bug', 0], 
        "steel-beam": ['140', 'steel', 1], 
        "steel-roller": ['130', 'steel', 0], 
        "steel-wing": ['70', 'steel', 0], 
        "sticky-web": [0, 'bug', 2], 
        "stockpile": [0, 'normal', 2], 
        "stomp": ['65', 'normal', 0], 
        "stomping-tantrum": ['75', 'ground', 0], 
        "stone-axe": ['65', 'rock', 0], 
        "stone-edge": ['100', 'rock', 0], 
        "stored-power": ['20', 'psychic', 1], 
        "storm-throw": ['60', 'fighting', 0], 
        "strange-steam": ['90', 'fairy', 1], 
        "strength": ['80', 'normal', 0], 
        "strength-sap": [0, 'grass', 2], 
        "string-shot": [0, 'bug', 2], 
        "struggle": ['50', 'normal', 0], 
        "struggle-bug": ['50', 'bug', 1], 
        "stuff-cheeks": [0, 'normal', 2], 
        "stun-spore": [0, 'grass', 2], 
        "submission": ['80', 'fighting', 0], 
        "substitute": [0, 'normal', 2], 
        "sucker-punch": ['70', 'dark', 0], 
        "sunny-day": [0, 'fire', 2], 
        "sunsteel-strike": ['100', 'steel', 0], 
        "super-fang": [0, 'normal', 0], 
        "supercell-slam": ['100', 'electric', 0], 
        "superpower": ['120', 'fighting', 0], 
        "supersonic": [0, 'normal', 2], 
        "surf": ['90', 'water', 1], 
        "surging-strikes": ['25', 'water', 0], 
        "swagger": [0, 'normal', 2], 
        "swallow": [0, 'normal', 2], 
        "sweet-kiss": [0, 'fairy', 2], 
        "sweet-scent": [0, 'normal', 2], 
        "swift": ['60', 'normal', 1], 
        "switcheroo": [0, 'dark', 2], 
        "swords-dance": [0, 'normal', 2], 
        "synchronoise": ['120', 'psychic', 1], 
        "synthesis": [0, 'grass', 2], 
        "syrup-bomb": ['60', 'grass', 1], 
        "tachyon-cutter": ['50', 'steel', 1], 
        "tackle": ['40', 'normal', 0], 
        "tail-glow": [0, 'bug', 2], 
        "tail-slap": ['25', 'normal', 0], 
        "tail-whip": [0, 'normal', 2], 
        "tailwind": [0, 'flying', 2], 
        "take-down": ['90', 'normal', 0], 
        "take-heart": [0, 'psychic', 2], 
        "tar-shot": [0, 'rock', 2], 
        "taunt": [0, 'dark', 2], 
        "tearful-look": [0, 'normal', 2], 
        "teatime": [0, 'normal', 2], 
        "techno-blast": ['120', 'normal', 1], 
        "teeter-dance": [0, 'normal', 2], 
        "telekinesis": [0, 'psychic', 2], 
        "teleport": [0, 'psychic', 2], 
        "temper-flare": ['75', 'fire', 0], 
        "tera-blast": ['80', 'normal', 1], 
        "tera-starstorm": ['120', 'normal', 1], 
        "terrain-pulse": ['50', 'normal', 1], 
        "thief": ['60', 'dark', 0], 
        "thousand-arrows": ['90', 'ground', 0], 
        "thousand-waves": ['90', 'ground', 0], 
        "thrash": ['120', 'normal', 0], 
        "throat-chop": ['80', 'dark', 0], 
        "thunder": ['110', 'electric', 1], 
        "thunder-cage": ['80', 'electric', 1], 
        "thunder-fang": ['65', 'electric', 0], 
        "thunder-punch": ['75', 'electric', 0], 
        "thunder-shock": ['40', 'electric', 1], 
        "thunder-wave": [0, 'electric', 2], 
        "thunderbolt": ['90', 'electric', 1], 
        "thunderclap": ['70', 'electric', 1], 
        "thunderous-kick": ['90', 'fighting', 0], 
        "tickle": [0, 'normal', 2], 
        "tidy-up": [0, 'normal', 2], 
        "topsy-turvy": [0, 'dark', 2], 
        "torch-song": ['80', 'fire', 1], 
        "torment": [0, 'dark', 2], 
        "toxic": [0, 'poison', 2], 
        "toxic-spikes": [0, 'poison', 2], 
        "toxic-thread": [0, 'poison', 2], 
        "trailblaze": ['50', 'grass', 0], 
        "transform": [0, 'normal', 2], 
        "tri-attack": ['80', 'normal', 1], 
        "trick": [0, 'psychic', 2], 
        "trick-room": [0, 'psychic', 2], 
        "trick-or-treat": [0, 'ghost', 2], 
        "triple-arrows": ['90', 'fighting', 0], 
        "triple-axel": ['20', 'ice', 0], 
        "triple-dive": ['30', 'water', 0], 
        "triple-kick": ['10', 'fighting', 0], 
        "trop-kick": ['70', 'grass', 0], 
        "trump-card": [0, 'normal', 1], 
        "twin-beam": ['40', 'psychic', 1], 
        "twineedle": ['25', 'bug', 0], 
        "twister": ['40', 'dragon', 1], 
        "u-turn": ['70', 'bug', 0], 
        "upper-hand": ['65', 'fighting', 0], 
        "uproar": ['90', 'normal', 1], 
        "v-create": ['180', 'fire', 0], 
        "vacuum-wave": ['40', 'fighting', 1], 
        "veevee-volley": [0, 'normal', 0], 
        "venom-drench": [0, 'poison', 2], 
        "venoshock": ['65', 'poison', 1], 
        "victory-dance": [0, 'fighting', 2], 
        "vine-whip": ['45', 'grass', 0], 
        "vise-grip": ['55', 'normal', 0], 
        "vital-throw": ['70', 'fighting', 0], 
        "volt-switch": ['70', 'electric', 1], 
        "volt-tackle": ['120', 'electric', 0], 
        "wake-up-slap": ['70', 'fighting', 0], 
        "water-gun": ['40', 'water', 1], 
        "water-pledge": ['80', 'water', 1], 
        "water-pulse": ['60', 'water', 1], 
        "water-shuriken": ['15', 'water', 1], 
        "water-sport": [0, 'water', 2], 
        "water-spout": ['150', 'water', 1], 
        "waterfall": ['80', 'water', 0], 
        "wave-crash": ['120', 'water', 0], 
        "weather-ball": ['50', 'normal', 1], 
        "whirlpool": ['35', 'water', 1], 
        "whirlwind": [0, 'normal', 2], 
        "wicked-blow": ['75', 'dark', 0], 
        "wicked-torque": ['80', 'dark', 0], 
        "wide-guard": [0, 'rock', 2], 
        "wild-charge": ['90', 'electric', 0], 
        "wildbolt-storm": ['100', 'electric', 1], 
        "will-o-wisp": [0, 'fire', 2], 
        "wing-attack": ['60', 'flying', 0], 
        "wish": [0, 'normal', 2], 
        "withdraw": [0, 'water', 2], 
        "wonder-room": [0, 'psychic', 2], 
        "wood-hammer": ['120', 'grass', 0], 
        "work-up": [0, 'normal', 2], 
        "worry-seed": [0, 'grass', 2], 
        "wrap": ['15', 'normal', 0], 
        "wring-out": [0, 'normal', 1], 
        "x-scissor": ['80', 'bug', 0], 
        "yawn": [0, 'normal', 2], 
        "zap-cannon": ['120', 'electric', 1], 
        "zen-headbutt": ['80', 'psychic', 0], 
        "zing-zap": ['80', 'electric', 0], 
        "zippy-zap": ['50', 'electric', 0]
    }

    with open('moveEffects', 'wb') as file:
        pickle.dump(movesMap, file)

    with open('moveEffects', 'rb') as file: 
        print(pickle.load(file))

    type_chart = {
        "normal": {
            "rock": 0.5,
            "ghost": 0.0
        },
        "fire": {
            "fire": 0.5,
            "water": 0.5,
            "grass": 2.0,
            "ice": 2.0,
            "bug": 2.0,
            "rock": 0.5,
            "dragon": 0.5
        },
        "water": {
            "fire": 2.0,
            "water": 0.5,
            "grass": 0.5,
            "ground": 2.0,
            "rock": 2.0,
            "dragon": 0.5
        },
        "electric": {
            "water": 2.0,
            "grass": 0.5,
            "electric": 0.5,
            "ground": 0.0,
            "flying": 2.0,
            "dragon": 0.5
        },
        "grass": {
            "fire": 0.5,
            "water": 2.0,
            "grass": 0.5,
            "poison": 0.5,
            "ground": 2.0,
            "flying": 0.5,
            "bug": 0.5,
            "rock": 2.0,
            "dragon": 0.5
        },
        "ice": {
            "fire": 0.5,
            "water": 0.5,
            "grass": 2.0,
            "ice": 0.5,
            "ground": 2.0,
            "flying": 2.0,
            "dragon": 2.0
        },
        "fighting": {
            "normal": 2.0,
            "ice": 2.0,
            "poison": 0.5,
            "flying": 0.5,
            "psychic": 0.5,
            "bug": 0.5,
            "rock": 2.0,
            "ghost": 0.0
        },
        "poison": {
            "grass": 2.0,
            "poison": 0.5,
            "ground": 0.5,
            "bug": 2.0,
            "rock": 0.5,
            "ghost": 0.5
        },
        "ground": {
            "fire": 2.0,
            "grass": 0.5,
            "electric": 2.0,
            "poison": 2.0,
            "flying": 0.0,
            "bug": 0.5,
            "rock": 2.0
        },
        "flying": {
            "electric": 0.5,
            "grass": 2.0,
            "fighting": 2.0,
            "bug": 2.0,
            "rock": 0.5
        },
        "psychic": {
            "fighting": 2.0,
            "poison": 2.0,
            "psychic": 0.5
        },
        "bug": {
            "fire": 0.5,
            "grass": 2.0,
            "fighting": 0.5,
            "poison": 2.0,
            "flying": 0.5,
            "psychic": 2.0,
            "ghost": 0.5
        },
        "rock": {
            "fire": 2.0,
            "ice": 2.0,
            "fighting": 0.5,
            "ground": 0.5,
            "flying": 2.0,
            "bug": 2.0
        },
        "ghost": {
            "normal": 0.0,
            "psychic": 2.0,
            "ghost": 2.0
        },
        "dragon": {
            "dragon": 2.0
        }
    }

    with open('typeChart', 'wb') as file:
        pickle.dump(type_chart, file)

    with open('typeChart', 'rb') as file: 
        print(pickle.load(file))

main()